### ISSUE TITLE
Error while running: seek() on closed filehandle ARGV

### ISSUE THREAD

**Issue by jjulian** [priithaamer/rubydictionary#1]
See terminal log in https://gist.github.com/5b192510b7b47782dc0b

No dictionary file is created. It looks like `seek() on closed filehandle ARGV at /Developer/Extras/Dictionary Development Kit/bin/make_line.pl` is expecting ARGV to be set. 

MacOS 10.7.1 xcode 4.2

**Comment by attilagyorffy** [comment]
Having a very similar issue here, it happens when I am trying to generate the documentation for Capybara 1.1.1 on 10.7.2 and XCode 4.2 (using Ruby 1.9.2).

Terminal output: https://gist.github.com/1287471

What other information do you need me to provide in order to help debugging the issue?

**Comment by ivanoats** [comment]
I have this issue too, any progress?
